"use client"
import './globals.css'
import { useState } from 'react'
import { BsMoonFill, BsSunFill } from 'react-icons/bs'
import Footer from './components/Footer'


// import { Inter } from 'next/font/google'
// const inter = Inter({ subsets: ['latin'] })

export const details = {
  title: 'Mma Tv',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  const [isNightMode, setIsNightMode] = useState(false);
  
  const toggleTheme = () => {
    setIsNightMode(prevMode => !prevMode);
  };
  return (
    <html lang="en">
      <body className={`${isNightMode ? 'bg-black' : 'bg-gray-100'}`}>
      <div className={`flex justify-between p-5 text-${isNightMode ? 'white' : 'black'} font-semibold text-3xl mb-4`}>
      <p className='flex justify-between ' onClick={toggleTheme}> {isNightMode ? <BsMoonFill style={{color: 'whitesmoke'}}/> : <BsSunFill style={{color: ''}}/>}</p>
      
      {children}
    </div>
    <div><Footer /> </div>
      </body>
    </html>
  )
}
